apiVersion: v1 
kind: Service 
metadata: 
  name: dxemssql-primary-0 
spec: 
  type: LoadBalancer 
  selector:
    #Assigns load balancer to specific pod
    statefulset.kubernetes.io/pod-name: dxemssql-primary-0 
  ports: 
    #SQL Server port
  - name: sql 
    protocol: TCP 
    port: 1433 
    targetPort: 1433
    #SQL listener port
  - name: listener
    protocol: TCP
    port: 14033
    targetPort: 14033
    #DxEnterprise admin port
  - name: dxe 
    protocol: TCP 
    port: 7979 
    targetPort: 7979
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: dxemssql-secondary-0 
spec: 
  type: LoadBalancer 
  selector: 
    statefulset.kubernetes.io/pod-name: dxemssql-secondary-0 
  ports: 
  - name: sql 
    protocol: TCP 
    port: 1433 
    targetPort: 1433 
  - name: listener
    protocol: TCP
    port: 14033
    targetPort: 14033
  - name: dxe 
    protocol: TCP 
    port: 7979 
    targetPort: 7979 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: dxemssql-secondary-1 
spec: 
  type: LoadBalancer 
  selector: 
    statefulset.kubernetes.io/pod-name: dxemssql-secondary-1 
  ports: 
  - name: sql 
    protocol: TCP 
    port: 1433 
    targetPort: 1433 
  - name: listener
    protocol: TCP
    port: 14033
    targetPort: 14033
  - name: dxe 
    protocol: TCP 
    port: 7979 
    targetPort: 7979
