# Default values for dxemssql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#General
replicas: 3
secretKeys: null
enableLoadBalancers: "true"

#SQL Server settings
ACCEPT_EULA: "Y"
MSSQL_AGENT_ENABLED: "false"

#DxEnterprise settings
repository: dh2i/dxemssql
pullPolicy: Always
tag: latest
DX_LICENSE: null
DX_VHOST_NAME: "VHOST1"
DX_AG_NAME: "AG1"
DX_NEW_CLUSTER: "true"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
